name: Run FDA Scraper Daily

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Create Google Credentials File
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account_credentials.json

      - name: Run Python Scraper
        run: python web_scraper_to_sheets.py
