name: Run FDA Scraper Daily

on:
  schedule:
    # 매일 새벽 1시(UTC 기준)에 실행됩니다. 한국 시간으로는 오전 10시입니다.
    # 시간을 바꾸고 싶으면 앞의 숫자 '1'을 조절하세요. (0-23)
    - cron: '0 1 * * *'
  # 수동으로도 실행할 수 있도록 workflow_dispatch 추가
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest # 우분투 최신 버전에서 실행

    steps:
      # 1. 저장소의 코드를 가상 머신으로 가져오기
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 파이썬 설치
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Google Chrome 및 ChromeDriver 설치 (Selenium 실행에 필수!)
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      # 4. 필요한 파이썬 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # 5. GitHub Secrets에 저장된 인증 정보를 파일로 만들기
      - name: Create Google Credentials File
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > service_account_credentials.json

      # 6. 파이썬 스크립트 실행
      - name: Run Python Scraper
        run: python web_scraper_to_sheets.py
